A="{:d}".format(52)
B="{:5d}".format(52)
C="{:10d}".format(52)
D="{:05d}".format(52)
E="{:05d}".format(-52)
print("#Basic")
print(A)
print("Output in particular blank")
print(B)
print(C)
print("input 0 into empty space")
print(D)
print(E)